# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import codex_pb2 as codex__pb2

GRPC_GENERATED_VERSION = '1.71.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in codex_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CodexServiceStub(object):
    """Service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListTools = channel.unary_unary(
                '/codex.CodexService/ListTools',
                request_serializer=codex__pb2.ListToolsRequest.SerializeToString,
                response_deserializer=codex__pb2.ListToolsResponse.FromString,
                _registered_method=True)
        self.CallTool = channel.unary_unary(
                '/codex.CodexService/CallTool',
                request_serializer=codex__pb2.ToolCallRequest.SerializeToString,
                response_deserializer=codex__pb2.ToolCallResponse.FromString,
                _registered_method=True)
        self.StreamTool = channel.unary_stream(
                '/codex.CodexService/StreamTool',
                request_serializer=codex__pb2.StreamToolRequest.SerializeToString,
                response_deserializer=codex__pb2.StreamResponse.FromString,
                _registered_method=True)
        self.ListServers = channel.unary_unary(
                '/codex.CodexService/ListServers',
                request_serializer=codex__pb2.ListServersRequest.SerializeToString,
                response_deserializer=codex__pb2.ListServersResponse.FromString,
                _registered_method=True)
        self.GetServerStatus = channel.unary_unary(
                '/codex.CodexService/GetServerStatus',
                request_serializer=codex__pb2.GetServerStatusRequest.SerializeToString,
                response_deserializer=codex__pb2.ServerStatus.FromString,
                _registered_method=True)
        self.AddServer = channel.unary_unary(
                '/codex.CodexService/AddServer',
                request_serializer=codex__pb2.AddServerRequest.SerializeToString,
                response_deserializer=codex__pb2.AddServerResponse.FromString,
                _registered_method=True)
        self.RemoveServer = channel.unary_unary(
                '/codex.CodexService/RemoveServer',
                request_serializer=codex__pb2.RemoveServerRequest.SerializeToString,
                response_deserializer=codex__pb2.RemoveServerResponse.FromString,
                _registered_method=True)
        self.Exec = channel.unary_unary(
                '/codex.CodexService/Exec',
                request_serializer=codex__pb2.ExecRequest.SerializeToString,
                response_deserializer=codex__pb2.ExecResponse.FromString,
                _registered_method=True)
        self.ExecStream = channel.unary_stream(
                '/codex.CodexService/ExecStream',
                request_serializer=codex__pb2.ExecRequest.SerializeToString,
                response_deserializer=codex__pb2.ExecStreamResponse.FromString,
                _registered_method=True)
        self.ApplyPatch = channel.unary_unary(
                '/codex.CodexService/ApplyPatch',
                request_serializer=codex__pb2.ApplyPatchRequest.SerializeToString,
                response_deserializer=codex__pb2.ApplyPatchResponse.FromString,
                _registered_method=True)
        self.CreateSession = channel.unary_unary(
                '/codex.CodexService/CreateSession',
                request_serializer=codex__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=codex__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/codex.CodexService/GetSession',
                request_serializer=codex__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=codex__pb2.SessionInfo.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/codex.CodexService/ListSessions',
                request_serializer=codex__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=codex__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.CloseSession = channel.unary_unary(
                '/codex.CodexService/CloseSession',
                request_serializer=codex__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=codex__pb2.CloseSessionResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/codex.CodexService/HealthCheck',
                request_serializer=codex__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=codex__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.WatchHealth = channel.unary_stream(
                '/codex.CodexService/WatchHealth',
                request_serializer=codex__pb2.WatchHealthRequest.SerializeToString,
                response_deserializer=codex__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/codex.CodexService/GetConfig',
                request_serializer=codex__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=codex__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.UpdateConfig = channel.unary_unary(
                '/codex.CodexService/UpdateConfig',
                request_serializer=codex__pb2.UpdateConfigRequest.SerializeToString,
                response_deserializer=codex__pb2.UpdateConfigResponse.FromString,
                _registered_method=True)
        self.SubscribeEvents = channel.unary_stream(
                '/codex.CodexService/SubscribeEvents',
                request_serializer=codex__pb2.EventSubscribeRequest.SerializeToString,
                response_deserializer=codex__pb2.EventEnvelope.FromString,
                _registered_method=True)
        self.WatchApprovals = channel.unary_stream(
                '/codex.CodexService/WatchApprovals',
                request_serializer=codex__pb2.Empty.SerializeToString,
                response_deserializer=codex__pb2.ApprovalRequestMsg.FromString,
                _registered_method=True)
        self.RespondApproval = channel.unary_unary(
                '/codex.CodexService/RespondApproval',
                request_serializer=codex__pb2.RespondApprovalRequest.SerializeToString,
                response_deserializer=codex__pb2.RespondApprovalResponse.FromString,
                _registered_method=True)


class CodexServiceServicer(object):
    """Service definition
    """

    def ListTools(self, request, context):
        """Tool management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CallTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTool(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListServers(self, request, context):
        """Server management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetServerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveServer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Exec(self, request, context):
        """Exec
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecStream(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ApplyPatch(self, request, context):
        """Patch
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSession(self, request, context):
        """Session management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """Health checks
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubscribeEvents(self, request, context):
        """Events and approvals
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WatchApprovals(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RespondApproval(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CodexServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListTools': grpc.unary_unary_rpc_method_handler(
                    servicer.ListTools,
                    request_deserializer=codex__pb2.ListToolsRequest.FromString,
                    response_serializer=codex__pb2.ListToolsResponse.SerializeToString,
            ),
            'CallTool': grpc.unary_unary_rpc_method_handler(
                    servicer.CallTool,
                    request_deserializer=codex__pb2.ToolCallRequest.FromString,
                    response_serializer=codex__pb2.ToolCallResponse.SerializeToString,
            ),
            'StreamTool': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTool,
                    request_deserializer=codex__pb2.StreamToolRequest.FromString,
                    response_serializer=codex__pb2.StreamResponse.SerializeToString,
            ),
            'ListServers': grpc.unary_unary_rpc_method_handler(
                    servicer.ListServers,
                    request_deserializer=codex__pb2.ListServersRequest.FromString,
                    response_serializer=codex__pb2.ListServersResponse.SerializeToString,
            ),
            'GetServerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetServerStatus,
                    request_deserializer=codex__pb2.GetServerStatusRequest.FromString,
                    response_serializer=codex__pb2.ServerStatus.SerializeToString,
            ),
            'AddServer': grpc.unary_unary_rpc_method_handler(
                    servicer.AddServer,
                    request_deserializer=codex__pb2.AddServerRequest.FromString,
                    response_serializer=codex__pb2.AddServerResponse.SerializeToString,
            ),
            'RemoveServer': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveServer,
                    request_deserializer=codex__pb2.RemoveServerRequest.FromString,
                    response_serializer=codex__pb2.RemoveServerResponse.SerializeToString,
            ),
            'Exec': grpc.unary_unary_rpc_method_handler(
                    servicer.Exec,
                    request_deserializer=codex__pb2.ExecRequest.FromString,
                    response_serializer=codex__pb2.ExecResponse.SerializeToString,
            ),
            'ExecStream': grpc.unary_stream_rpc_method_handler(
                    servicer.ExecStream,
                    request_deserializer=codex__pb2.ExecRequest.FromString,
                    response_serializer=codex__pb2.ExecStreamResponse.SerializeToString,
            ),
            'ApplyPatch': grpc.unary_unary_rpc_method_handler(
                    servicer.ApplyPatch,
                    request_deserializer=codex__pb2.ApplyPatchRequest.FromString,
                    response_serializer=codex__pb2.ApplyPatchResponse.SerializeToString,
            ),
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=codex__pb2.CreateSessionRequest.FromString,
                    response_serializer=codex__pb2.SessionInfo.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=codex__pb2.GetSessionRequest.FromString,
                    response_serializer=codex__pb2.SessionInfo.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=codex__pb2.ListSessionsRequest.FromString,
                    response_serializer=codex__pb2.ListSessionsResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=codex__pb2.CloseSessionRequest.FromString,
                    response_serializer=codex__pb2.CloseSessionResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=codex__pb2.HealthCheckRequest.FromString,
                    response_serializer=codex__pb2.HealthCheckResponse.SerializeToString,
            ),
            'WatchHealth': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchHealth,
                    request_deserializer=codex__pb2.WatchHealthRequest.FromString,
                    response_serializer=codex__pb2.HealthCheckResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=codex__pb2.GetConfigRequest.FromString,
                    response_serializer=codex__pb2.GetConfigResponse.SerializeToString,
            ),
            'UpdateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateConfig,
                    request_deserializer=codex__pb2.UpdateConfigRequest.FromString,
                    response_serializer=codex__pb2.UpdateConfigResponse.SerializeToString,
            ),
            'SubscribeEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.SubscribeEvents,
                    request_deserializer=codex__pb2.EventSubscribeRequest.FromString,
                    response_serializer=codex__pb2.EventEnvelope.SerializeToString,
            ),
            'WatchApprovals': grpc.unary_stream_rpc_method_handler(
                    servicer.WatchApprovals,
                    request_deserializer=codex__pb2.Empty.FromString,
                    response_serializer=codex__pb2.ApprovalRequestMsg.SerializeToString,
            ),
            'RespondApproval': grpc.unary_unary_rpc_method_handler(
                    servicer.RespondApproval,
                    request_deserializer=codex__pb2.RespondApprovalRequest.FromString,
                    response_serializer=codex__pb2.RespondApprovalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'codex.CodexService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('codex.CodexService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CodexService(object):
    """Service definition
    """

    @staticmethod
    def ListTools(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/ListTools',
            codex__pb2.ListToolsRequest.SerializeToString,
            codex__pb2.ListToolsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CallTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/CallTool',
            codex__pb2.ToolCallRequest.SerializeToString,
            codex__pb2.ToolCallResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTool(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codex.CodexService/StreamTool',
            codex__pb2.StreamToolRequest.SerializeToString,
            codex__pb2.StreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListServers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/ListServers',
            codex__pb2.ListServersRequest.SerializeToString,
            codex__pb2.ListServersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetServerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/GetServerStatus',
            codex__pb2.GetServerStatusRequest.SerializeToString,
            codex__pb2.ServerStatus.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/AddServer',
            codex__pb2.AddServerRequest.SerializeToString,
            codex__pb2.AddServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveServer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/RemoveServer',
            codex__pb2.RemoveServerRequest.SerializeToString,
            codex__pb2.RemoveServerResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Exec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/Exec',
            codex__pb2.ExecRequest.SerializeToString,
            codex__pb2.ExecResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ExecStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codex.CodexService/ExecStream',
            codex__pb2.ExecRequest.SerializeToString,
            codex__pb2.ExecStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ApplyPatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/ApplyPatch',
            codex__pb2.ApplyPatchRequest.SerializeToString,
            codex__pb2.ApplyPatchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/CreateSession',
            codex__pb2.CreateSessionRequest.SerializeToString,
            codex__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/GetSession',
            codex__pb2.GetSessionRequest.SerializeToString,
            codex__pb2.SessionInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/ListSessions',
            codex__pb2.ListSessionsRequest.SerializeToString,
            codex__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/CloseSession',
            codex__pb2.CloseSessionRequest.SerializeToString,
            codex__pb2.CloseSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/HealthCheck',
            codex__pb2.HealthCheckRequest.SerializeToString,
            codex__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchHealth(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codex.CodexService/WatchHealth',
            codex__pb2.WatchHealthRequest.SerializeToString,
            codex__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/GetConfig',
            codex__pb2.GetConfigRequest.SerializeToString,
            codex__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/UpdateConfig',
            codex__pb2.UpdateConfigRequest.SerializeToString,
            codex__pb2.UpdateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubscribeEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codex.CodexService/SubscribeEvents',
            codex__pb2.EventSubscribeRequest.SerializeToString,
            codex__pb2.EventEnvelope.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WatchApprovals(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/codex.CodexService/WatchApprovals',
            codex__pb2.Empty.SerializeToString,
            codex__pb2.ApprovalRequestMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RespondApproval(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/codex.CodexService/RespondApproval',
            codex__pb2.RespondApprovalRequest.SerializeToString,
            codex__pb2.RespondApprovalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
